version: "3.9"
services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    networks:
      - backend
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env
    restart: always

  wordpress:
    depends_on:
      - mariadb
      - redis
    container_name: wordpress
    build: ./requirements/wordpress/
    networks:
      - frontend
      - backend
    ports:
      - 9000:9000
    volumes:
      - wp:/var/www/html/wordpress
    env_file:
      - .env
    restart: always

  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build: ./requirements/nginx/
    networks:
      - frontend
    ports:
      - 443:443
    volumes:
      - wp:/var/www/html/wordpress
    env_file:
      - .env
    restart: always
  
  redis:
    container_name: redis
    build:
      context: ./requirements/redis
    networks:
      - backend
    ports:
      - 6379:6379
    env_file:
      - .env
    restart: always

  # ftp:
  #   container_name: ftp
  #   build:
  #     context: ./requirements/ftp
  #   networks:
  #     - backend
  #   ports:
  #     - 20:20
  #     - 21:21
  #   volumes:
  #     - wp:/var/www/html/wordpress
  #   env_file:
  #     - .env
  #   restart: always

networks:
  frontend:
    name: frontend
  backend:
    name: backend

volumes:
  db:
    driver_opts:
      type: none
      o: bind
      device: /home/jihoh/data/db
  wp:
    driver_opts:
      type: none
      o: bind
      device: /home/jihoh/data/wp