version: "3.9"
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - frontend

networks:
  frontend:
    name: frontend
  backend:
    name: backend