version: "3.9"
services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    ports:
      - 3306:3306
    networks:
      - backend
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env
    restart: always

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: ./requirements/wordpress/
    ports:
      - "9000:9000"
    networks:
      - frontend
      - backend
    volumes:
      - wp:/var/www/html/wordpress
    env_file:
      - .env
    restart: always

  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - 443:443
    networks:
      - frontend
    volumes:
      - wp:/var/www/html/wordpress
    env_file:
      - .env
    restart: always

networks:
  frontend:
    name: frontend
  backend:
    name: backend

volumes:
  db:
    driver_opts:
      type: none
      o: bind
      device: /home/jihoh/data/db
  wp:
    driver_opts:
      type: none
      o: bind
      device: /home/jihoh/data/wp