version: "3.9"
services:
  nginx:
    depends_on:
      - goaccess
    container_name: nginx
    build: ./requirements/nginx/
    networks:
      - 42net
    ports:
      - 80:80
      - 443:443
    volumes:
      - wp:/var/www/html/wordpress
      - log:/var/log/nginx
    env_file:
      - .env
    restart: always

  goaccess:
    container_name: goaccess
    build:
      context: ./requirements/bonus/goaccess
    networks:
      - 42net
    ports:
      - 7000:7000
      - 7890:7890
    volumes:
      - log:/var/log/nginx
    env_file:
      - .env
    restart: always

networks:
  42net:
    name: 42net
    driver: bridge

volumes:
  db:
    driver_opts:
      type: none
      o: bind
      device: /home/jihoh/data/db
  wp:
    driver_opts:
      type: none
      o: bind
      device: /home/jihoh/data/wp
  log:
    driver_opts:
      type: none
      o: bind
      device: /home/jihoh/data/log