CREATE DATABASE IF NOT EXISTS {$WP_DB_NAME};
CREATE USER IF NOT EXISTS '{$WP_ADMIN}'@'%' IDENTIFIED BY '{$WP_ADMIN_PASSWORD}';
GRANT ALL PRIVILEGES ON {$WP_DB_NAME}.* TO '{$WP_ADMIN}'@'%';
SET PASSWORD FOR 'root'@'localhost' = PASSWORD('{$WP_ADMIN_PASSWORD}');
FLUSH PRIVILEGES;