CREATE DATABASE IF NOT EXISTS {$WP_DB_NAME};
CREATE USER IF NOT EXISTS '{$WP_ADMIN}'@'localhost' IDENTIFIED BY '{$WP_ADMIN_PASSWORD}';
GRANT ALL PRIVILEGES ON {$WP_DB_NAME}.* TO '{$WP_ADMIN}'@'localhost';
FLUSH PRIVILEGES;